
CREATE TABLE IF NOT EXISTS `reports` (
  `s_id` varchar(11) NOT NULL,
  `TeamNum` INT(3) NULL DEFAULT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Status` MEDIUMTEXT NULL DEFAULT NULL,
  `Blockers` MEDIUMTEXT NULL DEFAULT NULL,
  `Time Log` INT(11) NULL DEFAULT NULL,
  `Team Health` VARCHAR(45) NULL DEFAULT NULL,
  `Concerns` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`s_id`))

