CREATE TABLE `grades` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  FOREIGN KEY (`ID`) REFERENCES reports(`ID`),
  `grade` int(3) DEFAULT NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
